apiVersion: apps/v1
kind: Deployment
metadata:
  name: jar-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jar-microservice
  template:
    metadata:
      labels:
        app: jar-microservice
    spec:
      containers:
        - name: jar-microservice
          image: 207567773705.dkr.ecr.us-east-1.amazonaws.com/backend:latest
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: jar-microservice-nodeport
spec:
  type: NodePort
  selector:
    app: jar-microservice
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 30080